name: Generate Test Coverage

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammati/php-action@v1.4
        with:
          version: '8.1'

      - name: Install Composer dependencies
        run: composer install

      - name: Run tests with coverage
        run: vendor/bin/phpunit --coverage-html coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/