name: Laravel Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-start-period=30s

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Set up PHP with required version and extensions
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath, pcntl, zip

      # Install Composer dependencies
      - name: Install Dependencies
        run: composer update --prefer-dist --no-progress --no-suggest --ansi

      # Node JS Setup
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install NPM
      - name: Install npm dependencies
        run: npm install

      # Compile Assets
      - name: Compile assets
        run: npm run build  # Or `npm run dev` based on your setup
          
      # Setting Firebase credentials
      - name: Set up Firebase credentials
        run: |
          mkdir -p public/storage
          echo "$FIREBASE_CREDENTIALS_JSON" > public/storage/firebase_credentials.json
        env:
          FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
      # Copy .env file
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # Generate Application Key
      - name: Generate Application Key
        run: php artisan key:generate

      # Set permissions for storage and cache
      - name: Set Directory Permissions
        run: chmod -R 777 storage bootstrap/cache


      # Update database configuration to MySQL
      - name: Set MySQL Database Configurations
        run: |
          sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' .env
          sed -i 's/DB_DATABASE=database.sqlite/DB_DATABASE=laravel/' .env
          sed -i 's/DB_USERNAME=root/DB_USERNAME=user/' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=password/' .env

      # Wait for MySQL to be ready
      - name: Wait for MySQL to be ready
        run: |
          while ! mysqladmin -h 127.0.0.1 -u root -ppassword ping --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      # Run migrations
      - name: Run Migrations
        run: php artisan migrate --no-interaction --force

      # Run tests
      - name: Run Tests
        env:
          APP_ENV: testing
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: laravel
          DB_USERNAME: user
          DB_PASSWORD: password
          CACHE_DRIVER: array
          QUEUE_CONNECTION: sync
          SESSION_DRIVER: array
          MAIL_MAILER: array
        run: php artisan test
        continue-on-error: true 
