name: Générer la couverture des tests

on:
  push:
    branches: [ feature/GithubActionTestCoverage ]
  pull_request:
    branches: [ feature/GithubActionTestCoverage ]

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'  
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: imagick, swoole

      - name: Obtenir le code
        uses: actions/checkout@v3

      - name: Installer les dépendances
        run: composer install

      - name: Exécuter les tests avec couverture
        run: php artisan test --coverage --coverage-text

      - name: Générer le rapport de couverture HTML
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: ./coverage/coverage-text.html